export const EliteClothesLanding = [
    {
        id: 1,
        name: "Elitesmerch T-shirt Red",
        price: 150,
        isNew: false,
        img: "/cloths/toke1.png",
        discount: 10,
        category: "t-shirt",
        size: ["S", "M", "L", "XL", "XXL"],
        color: "Red",
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
    {
        id: 2,
        name: "Elitesmerch T-shirt Green",
        price: 150,
        img: "/cloths/toke2.jpg",
        discount: 10,
        isNew: false,
        category: "t-shirt",
        size: ["S", "M", "L", "XL", "XXL"],
        color: "Green",
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
    {
        id: 3,
        name: "Elitesmerch Sleeveless T-shirt Green",
        price: 150,
        img: "/cloths/toke4.jpg",
        discount: 0,
        size: ["S", "M", "L", "XL", "XXL"],
        color: "Black",
        isNew: false,
        category: "t-shirt",
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
    {
        id: 4,
        name: "Elitesmerch Head Warmer Blue ",
        price: 150,
        img: "/cloths/toke5.jpg",
        discount: 0,
        size: ["S", "M", "L", "XL", "XXL"],
        color: "Black",
        category: "cap",
        isNew: false,
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
    {
        id: 5,
        name: "Elitesmerch Head Warmer Gray ",
        price: 150,
        img: "/cloths/toke6.jpg",
        discount: 0,
        size: ["S", "M", "L", "XL", "XXL"],
        color: "Black",
        category: "cap",
        isNew: true,
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
    {
        id: 6,
        name: "Elitesmerch Head Warmer Green ",
        price: 150,
        img: "/cloths/toke7.jpg",
        discount: 0,
        size: ["S", "M", "L", "XL", "XXL"],
        color: "Black",
        category: "cap",
        isNew: true,
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
    {
        id: 7,
        name: "Elitesmerch Head Warmer Black ",
        price: 150,
        img: "/cloths/toke8.jpg",
        discount: 0,
        size: ["S", "M", "L", "XL", "XXL"],
        color: "Black",
        isNew: true,
        category: "cap",
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
    {
        id: 8,
        name: "Elitesmerch Head Warmer White ",
        price: 150,
        img: "/cloths/toke9.jpg",
        discount: 0,
        size: ["S", "M", "L", "XL", "XXL"],
        color: "Black",
        category: "cap",
        isNew: false,
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
    
    {
        id: 9,
        name: "Elitesmerch T-shirt Black with Red Logo ",
        price: 150,
        img: "/cloths/toke10.jpg",
        discount: 10,
        size: ["S", "M", "L", "XL", "XXL"],
        color: "Black",
        category: "t-shirt",
        isNew: true,
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
    {
        id: 10,
        name: "Elitesmerch T-shirt Black with Yellow Logo ",
        price: 150,
        img: "/cloths/toke11.jpg",
        discount: 0,
        size: ["S", "M", "L", "XL", "XXL"],
        color: "Black",
        isNew: false,
        category: "t-shirt",
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
    {
        id: 12,
        name: "Elitesmerch T-shirt ELMEJOR Black  ",
        price: 150,
        img: "/cloths/toke12.jpg",
        discount: 10,
        size: ["S", "M", "L", "XL", "XXL"],
        color: "Black",
        category: "t-shirt",
        isNew: false,
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
    {
        id: 13,
        name: "Elitesmerch T-shirt Kanu Printed Black  ",
        price: 150,
        img: "/cloths/toke13.jpg",
        discount: 10,
        size: ["S", "M", "L", "XL", "XXL"],
        color: "Black",
        category: "t-shirt",
        isNew: false,
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
    {
        id: 14,
        name: "Elitesmerch T-shirt Printed Black  ",
        price: 150,
        img: "/cloths/toke14.jpg",
        discount: 0,
        size: ["S", "M", "L", "XL", "XXL"],
        color: "Black",
        isNew: true,
        category: "t-shirt",
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
    
    {
        id: 15,
        name: "Elitesmerch Believe T-shirt Black  ",
        price: 150,
        img: "/cloths/toke15.jpg",
        discount: 10,
        size: ["S", "M", "L", "XL", "XXL"],
        color: "Black",
        category: "t-shirt",
        isNew: false,
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
    {
        id: 16,
        name: "Elitesmerch Caution Dept T-shirt Black  ",
        price: 150,
        img: "/cloths/toke16.jpg",
        discount: 0,
        size: ["S", "M", "L", "XL", "XXL"],
        color: "Black",
        category: "t-shirt",
        isNew: true,
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
    
    {
        id: 17,
        name: "Elitesmerch T-shirt  Black  ",
        price: 150,
        img: "/cloths/toke17.jpg",
        discount: 10,
        size: ["S", "M", "L", "XL", "XXL"],
        color: "Black",
        category: "t-shirt",
        isNew: true,
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
    
    {
        id: 18,
        name: "Elitesmerch Signature T-shirt  Black  ",
        price: 150,
        img: "/cloths/toke18.jpg",
        discount: 10,
        size: ["S", "M", "L", "XL", "XXL"],
        color: "Black",
        category: "t-shirt",
        isNew: false,
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
    
    {
        id: 19,
        name: "Elitesmerch Signature T-shirt  White  ",
        price: 150,
        img: "/cloths/toke23.jpg",
        discount: 10,
        size: ["S", "M", "L", "XL", "XXL"],
        color: "Black",
        category: "t-shirt",
        isNew: false,
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
    
    {
        id: 20,
        name: "Elitesmerch Jean Short Pant  Black  ",
        price: 150,
        img: "/cloths/toke19.jpg",
        discount: 10,
        size: ["S", "M", "L", "XL", "XXL"],
        color: "Black",
        category: "Shots",
        isNew: false,
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
    
    {
        id: 21,
        name: "Elitesmerch Flower T-shirt  Black  ",
        price: 150,
        img: "/cloths/toke20.jpg",
        discount: 10,
        size: ["S", "M", "L", "XL", "XXL"],
        color: "Black",
        category: "t-shirt",
        isNew: true,
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
    
    {
        id: 22,
        name: "Elitesmerch Signature T-shirt  White  ",
        price: 150,
        img: "/cloths/toke22.jpg",
        discount: 10,
        size: ["S", "M", "L", "XL", "XXL"],
        color: "wite",
        isNew: false,
        category: "t-shirt",
        description: "Pair it with your favorite bottoms for a versatile, stylish look that effortlessly transitions from day to night. Crafted with meticulous attention to detail, this shirt exudes understated elegance while making a bold statement with the iconic Elitesmerch logo at the front.",
        features: ["Black/White",
            "Premium Cotton",
            "Ribbed Crewneck",
            "Straight Hemline",
            "Short Sleeves"]
    },
]